fix: ts error.
fixing 'src/shape/edge.ts:66:43 ' and 'src/shape/edges/polyline.ts:25:45', TS2339:Property 'lineWidth' does not exist on type '{ stroke: string; lineAppendWidth: number; }'.